services:
  einsbym-api-gateway:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: einsbym-api-gateway
    ports:
      - 8888:8888
    networks:
      - einsbym-network
    environment:
      EINSBYM_SERVER_PORT: 8888
      EINSBYM_DB_HOST: einsbym-database
      EINSBYM_DB_PORT: 5432
      EINSBYM_DB_USER: postgres
      EINSBYM_DB_PASSWORD: root
      EINSBYM_DB_NAME: einsbym
      EINSBYM_DB_DDL_AUTO: update
      EINSBYM_DB_SHOW_SQL: true
      EINSBYM_STORAGE_SERVICE_HOST: einsbym-storage
      EINSBYM_STORAGE_SERVICE_PORT: 8080
      EINSBYM_API_HOST: einsbym-api
      EINSBYM_API_PORT: 4000

networks:
  einsbym-network:
    external: true
